# Generated by Django 4.1 on 2022-08-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Homoclave', models.CharField(max_length=20)),
                ('NombreTramite', models.CharField(max_length=150)),
                ('Tipo', models.CharField(max_length=30)),
                ('TipoTramite', models.CharField(max_length=100)),
                ('Depedencia', models.CharField(max_length=200)),
                ('UnidadAdministrativa', models.CharField(max_length=300)),
            ],
        ),
    ]
