# Generated by Django 4.1 on 2022-08-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgendarCita', models.CharField(max_length=2)),
                ('RealizarTramite', models.CharField(max_length=2)),
                ('MedioCita', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.IntegerField(max_length=4)),
                ('MonedaPago', models.CharField(max_length=20)),
                ('MetodologiaMonto', models.CharField(max_length=300)),
                ('RealizarPago', models.CharField(max_length=250)),
                ('FormaPago', models.CharField(max_length=100)),
                ('EtapaTramite', models.CharField(max_length=100)),
                ('VigenciaPago', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Homoclave', models.CharField(max_length=20)),
                ('NombreTramite', models.CharField(max_length=150)),
                ('Tipo', models.CharField(max_length=30)),
                ('TipoTramite', models.CharField(max_length=100)),
                ('Depedencia', models.CharField(max_length=200)),
                ('UnidadAdministrativa', models.CharField(max_length=300)),
                ('NivelGobierno', models.CharField(max_length=200)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Modalidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitudesRecibidas', models.IntegerField(max_length=10)),
                ('TotalSolicitudesRecibidas', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreFormato', models.CharField(max_length=100)),
                ('NumeroIdentificador', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentosJuridicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoVigencia', models.CharField(max_length=150)),
                ('Ambito', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=200)),
                ('Articulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentosJuridicos2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoPlazoMaximo', models.CharField(max_length=150)),
                ('Ambito', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=200)),
                ('Articulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentosJuridicos3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoInformacion', models.CharField(max_length=150)),
                ('Ambito', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=200)),
                ('Articulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentosJuridicos4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoInspeccion', models.CharField(max_length=150)),
                ('Ambito', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=200)),
                ('Articulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentosJuridicos5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoTramiteOServicio', models.CharField(max_length=150)),
                ('Ambito', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=200)),
                ('Articulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentosJuridicos6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoCriterio', models.CharField(max_length=150)),
                ('Ambito', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=200)),
                ('Articulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentosJuridicos7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoDerechos', models.CharField(max_length=150)),
                ('Ambito', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=200)),
                ('Articulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentosJuridicos8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoCanal', models.CharField(max_length=150)),
                ('Ambito', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=150)),
                ('Nombre', models.CharField(max_length=200)),
                ('Articulo', models.CharField(max_length=50)),
                ('RegristroRegulaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Informacion', models.CharField(max_length=100)),
                ('InformacionInteresado', models.CharField(max_length=150)),
                ('ProtestaCiudadana', models.CharField(max_length=100)),
                ('ProtestasAnual', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inspecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConservarInformacion', models.CharField(max_length=500)),
                ('TramiteInformacion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pasos', models.TextField(max_length=100)),
                ('Modalidades', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requisitos', models.CharField(max_length=300)),
                ('NombreRequisito', models.CharField(max_length=200)),
                ('OriginalCopia', models.CharField(max_length=300)),
                ('Descripcion', models.CharField(max_length=500)),
                ('Formato', models.CharField(max_length=20)),
                ('Naturaleza', models.CharField(max_length=20)),
                ('TiempoPromedio', models.FloatField(max_length=4)),
                ('FirmaValidacion', models.CharField(max_length=3)),
                ('PersonaEmite', models.CharField(max_length=100)),
                ('RequisitoSolicitado', models.CharField(max_length=20)),
                ('NombreDependencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResponsableTramite', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('RolFuncionario', models.CharField(max_length=30)),
                ('Cargo', models.CharField(max_length=50)),
                ('CorreoElectronico', models.CharField(max_length=60)),
                ('Otro', models.CharField(max_length=30)),
                ('Telefono', models.IntegerField(max_length=10)),
                ('Extension', models.IntegerField(max_length=6)),
                ('DatosResponsable', models.CharField(max_length=200)),
                ('QuejasDenuncias', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonaSolicitante', models.CharField(max_length=300)),
                ('FuncionalidadTramite', models.CharField(max_length=400)),
                ('CasoSolicitud', models.CharField(max_length=150)),
                ('ActividadEconomica', models.CharField(max_length=300)),
                ('Detalle', models.CharField(max_length=500)),
                ('Subsector', models.CharField(max_length=350)),
                ('Rama', models.CharField(max_length=300)),
                ('Subrama', models.CharField(max_length=150)),
                ('Clase', models.CharField(max_length=200)),
                ('Resolucion', models.CharField(max_length=300)),
                ('LigaTramite', models.CharField(max_length=200)),
                ('ResolucionRequisito', models.CharField(max_length=2)),
                ('LigaResolucion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tiempos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TiempoResolucion', models.IntegerField(max_length=10)),
                ('PlazoPrevenir', models.CharField(max_length=100)),
                ('PlazoResponder', models.IntegerField(max_length=10)),
                ('DerechoRespuesta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoResolucion', models.CharField(max_length=20)),
                ('Vigencia', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='tramite',
        ),
    ]
