# Generated by Django 4.0.4 on 2022-08-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datogeneral',
            name='modalidad',
        ),
    ]
