# Generated by Django 4.0.4 on 2022-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_datogeneral_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datogeneral',
            name='modalidades',
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='modalidades',
            field=models.ManyToManyField(to='posts.modalidad', verbose_name='Modalidad'),
        ),
    ]
