# Generated by Django 4.1 on 2022-08-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_cita_costo_datos_estadisticas_formato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='Monto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Extension',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tiempos',
            name='PlazoResponder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tiempos',
            name='TiempoResolucion',
            field=models.IntegerField(),
        ),
    ]
