# Generated by Django 4.1 on 2022-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_costo_monto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Homoclave', models.CharField(max_length=20, verbose_name='Homoclave')),
                ('NombreTramite', models.CharField(max_length=150, verbose_name='Nombre del trámite')),
                ('Tipo', models.CharField(max_length=30, verbose_name='Tipo')),
                ('TipoTramite', models.CharField(max_length=100, verbose_name='Tipo de trámite')),
                ('Depedencia', models.CharField(max_length=200, verbose_name='Depedencia')),
                ('UnidadAdministrativa', models.TextField(max_length=300, verbose_name='Unidad Administrativa')),
                ('NivelGobierno', models.CharField(max_length=200, verbose_name='Nivel de gobierno')),
                ('Descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('Modalidad', models.CharField(max_length=100, verbose_name='Modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitudesRecibidas', models.IntegerField(verbose_name='Número de solicitudes recibidas en el año anterior')),
                ('TotalSolicitudesRecibidas', models.IntegerField(verbose_name='Número de solicitudes recibidas')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoVigencia', models.CharField(max_length=150, verbose_name='Fundamento de la vigencia')),
                ('Ambito', models.CharField(max_length=100, verbose_name='Ámbito')),
                ('Tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('Articulo', models.CharField(max_length=50, verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentoJuridico2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoPlazoMaximo', models.CharField(max_length=150, verbose_name='Fundamento de la vigencia')),
                ('Ambito', models.CharField(max_length=100, verbose_name='Ámbito')),
                ('Tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('Articulo', models.CharField(max_length=50, verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentoJuridico3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoInformacion', models.CharField(max_length=150, verbose_name='Fundamento de la vigencia')),
                ('Ambito', models.CharField(max_length=100, verbose_name='Ámbito')),
                ('Tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('Articulo', models.CharField(max_length=50, verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentoJuridico4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoInspeccion', models.CharField(max_length=150, verbose_name='Fundamento de la vigencia')),
                ('Ambito', models.CharField(max_length=100, verbose_name='Ámbito')),
                ('Tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('Articulo', models.CharField(max_length=50, verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentoJuridico5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoTramiteOServicio', models.CharField(max_length=150, verbose_name='Fundamento de la vigencia')),
                ('Ambito', models.CharField(max_length=100, verbose_name='Ámbito')),
                ('Tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('Articulo', models.CharField(max_length=50, verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentoJuridico6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoCriterio', models.CharField(max_length=150, verbose_name='Fundamento de la vigencia')),
                ('Ambito', models.CharField(max_length=100, verbose_name='Ámbito')),
                ('Tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('Articulo', models.CharField(max_length=50, verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentoJuridico7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoDerechos', models.CharField(max_length=150, verbose_name='Fundamento de la vigencia')),
                ('Ambito', models.CharField(max_length=100, verbose_name='Ámbito')),
                ('Tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('Articulo', models.CharField(max_length=50, verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='FundamentoJuridico8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundamentoCanal', models.CharField(max_length=150, verbose_name='Fundamento de la vigencia')),
                ('Ambito', models.CharField(max_length=100, verbose_name='Ámbito')),
                ('Tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('Nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('Articulo', models.CharField(max_length=50, verbose_name='Artículo')),
                ('RegristroRegulaciones', models.CharField(max_length=100, verbose_name='Registro de regulaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConservarInformacion', models.TextField(max_length=500)),
                ('TramiteInformacion', models.TextField(max_length=300, verbose_name='¿Este trámite o servicio requiere conservar información para fines de acreditación, inspección y verificación con motivo del trámite o servicio?')),
            ],
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pasos', models.TextField(blank=True, max_length=250, verbose_name='Pasos')),
                ('Modalidades', models.CharField(max_length=100, verbose_name='Modalidades')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requisitos', models.TextField(blank=True, max_length=300, verbose_name='Requisitos')),
                ('NombreRequisito', models.CharField(blank=True, max_length=200, verbose_name='Nombre del requisito')),
                ('OriginalCopia', models.TextField(blank=True, max_length=300, verbose_name='Original o copia')),
                ('Descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('Formato', models.CharField(blank=True, max_length=20, verbose_name='Forma parte del formato')),
                ('Naturaleza', models.CharField(blank=True, max_length=20, verbose_name='Naturaleza')),
                ('TiempoPromedio', models.FloatField(blank=True, verbose_name='Tiempo promedio en conseguir el requisito para su presentación')),
                ('FirmaValidacion', models.CharField(blank=True, max_length=20, verbose_name='¿Es necesario alguna firma, validación, certificación, autorización o visto bueno de un tercero?')),
                ('PersonaEmite', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la empresa o persona que lo emite')),
                ('RequisitoSolicitado', models.CharField(blank=True, max_length=20, verbose_name='¿El requisito solicitado es un trámite que se debe realizar con alguna dependencia gubernamental?')),
                ('NombreDependencia', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la dependencia, ubicación y medios de contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TiempoResolucion', models.IntegerField(verbose_name='Tiempo que tiene la dependencia para resolver')),
                ('PlazoPrevenir', models.CharField(max_length=100, verbose_name='Plazo que tiene la dependencia para prevenir')),
                ('PlazoResponder', models.IntegerField(verbose_name='Plazo que tiene el usuario para responder la prevención')),
                ('DerechoRespuesta', models.CharField(max_length=30, verbose_name='Derecho del usuario ante la falta de respuesta')),
            ],
        ),
        migrations.DeleteModel(
            name='Datos',
        ),
        migrations.DeleteModel(
            name='Estadisticas',
        ),
        migrations.DeleteModel(
            name='FundamentosJuridicos',
        ),
        migrations.DeleteModel(
            name='FundamentosJuridicos2',
        ),
        migrations.DeleteModel(
            name='FundamentosJuridicos3',
        ),
        migrations.DeleteModel(
            name='FundamentosJuridicos4',
        ),
        migrations.DeleteModel(
            name='FundamentosJuridicos5',
        ),
        migrations.DeleteModel(
            name='FundamentosJuridicos6',
        ),
        migrations.DeleteModel(
            name='FundamentosJuridicos7',
        ),
        migrations.DeleteModel(
            name='FundamentosJuridicos8',
        ),
        migrations.DeleteModel(
            name='Inspecciones',
        ),
        migrations.DeleteModel(
            name='Pasos',
        ),
        migrations.DeleteModel(
            name='Requisitos',
        ),
        migrations.DeleteModel(
            name='Tiempos',
        ),
        migrations.AddField(
            model_name='responsableresolucion',
            name='Organo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Órgano interno de control'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='AgendarCita',
            field=models.CharField(max_length=2, verbose_name='¿Es obligatorio agendar una cita?'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='MedioCita',
            field=models.TextField(blank=True, max_length=500, verbose_name='Medio para solicitar la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='RealizarTramite',
            field=models.CharField(max_length=2, verbose_name='¿Se puede agendar una cita para realizar un trámite?'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='EtapaTramite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etapa del trámite o servicio en que se realiza o se puede realizar el trámite'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='FormaPago',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='MetodologiaMonto',
            field=models.TextField(max_length=300, verbose_name='Metodología para cálculo del monto'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='MonedaPago',
            field=models.CharField(max_length=20, verbose_name='Moneda en la que se realiza el pago'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='Monto',
            field=models.IntegerField(verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='RealizarPago',
            field=models.TextField(blank=True, max_length=250, verbose_name='¿En dónde puedo realizar el pago?'),
        ),
        migrations.AlterField(
            model_name='costo',
            name='VigenciaPago',
            field=models.CharField(blank=True, max_length=30, verbose_name='Vigencia de la línea de captura para realizar el pago en caso de requerirla'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='NombreFormato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del formato'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='NumeroIdentificador',
            field=models.IntegerField(verbose_name='Número de identificador del formato'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='Informacion',
            field=models.CharField(max_length=100, verbose_name='Información adicional'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='InformacionInteresado',
            field=models.CharField(max_length=150, verbose_name='Información que sea útil para que el interesado realice el trámite'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='ProtestaCiudadana',
            field=models.CharField(max_length=100, verbose_name='Protesta Ciudadana'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='ProtestasAnual',
            field=models.IntegerField(verbose_name='Cantidad de protestas recibidas al año'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Cargo',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='CorreoElectronico',
            field=models.EmailField(max_length=100, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='DatosResponsable',
            field=models.CharField(max_length=200, verbose_name='Datos de la oficina del responsable del trámite'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Extension',
            field=models.IntegerField(verbose_name='Extensión'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Otro',
            field=models.CharField(max_length=30, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='QuejasDenuncias',
            field=models.TextField(max_length=400, verbose_name='Datos de contacto para quejas y denuncias'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='ResponsableTramite',
            field=models.CharField(max_length=100, verbose_name='Responsable del trámite o servicio'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='RolFuncionario',
            field=models.CharField(max_length=30, verbose_name='Rol del funcionario'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='ActividadEconomica',
            field=models.TextField(max_length=300, verbose_name='Actividad económica que está vinculada al trámite o servicio'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='CasoSolicitud',
            field=models.CharField(max_length=150, verbose_name='¿En qué caso se debe solicitar el trámite o servicio?'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Clase',
            field=models.CharField(max_length=200, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Detalle',
            field=models.TextField(max_length=500, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='FuncionalidadTramite',
            field=models.TextField(max_length=400, verbose_name='¿Para qué sirve realizar este trámite?'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='LigaResolucion',
            field=models.CharField(max_length=100, verbose_name='Liga de la resolución del trámite'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='LigaTramite',
            field=models.CharField(max_length=200, verbose_name='Liga del trámite con que está vincualdo'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='PersonaSolicitante',
            field=models.TextField(max_length=300, verbose_name='¿Quién puede solicitarlo?'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Rama',
            field=models.TextField(max_length=300, verbose_name='Rama'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Resolucion',
            field=models.TextField(max_length=300, verbose_name='La resolución de este trámite está vinculada con la presentación de otros trámites'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='ResolucionRequisito',
            field=models.CharField(max_length=2, verbose_name='La resolución es requisito de otro trámite'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Subrama',
            field=models.CharField(max_length=150, verbose_name='Subrama'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Subsector',
            field=models.TextField(max_length=350, verbose_name='Subsector'),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='TipoResolucion',
            field=models.CharField(max_length=20, verbose_name='Tipo de resolución'),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='Vigencia',
            field=models.DateTimeField(verbose_name='Vigencia'),
        ),
    ]
