# Generated by Django 4.1 on 2022-08-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_dato_estadistica_fundamentojuridico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='TotalSolicitudesRecibidas',
            field=models.IntegerField(blank=True, verbose_name='Número de solicitudes recibidas'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='solicitudesRecibidas',
            field=models.IntegerField(blank=True, verbose_name='Número de solicitudes recibidas en el año anterior'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico',
            name='Ambito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico',
            name='Articulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico',
            name='FundamentoVigencia',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fundamento de la vigencia'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico',
            name='Nombre',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico',
            name='Tipo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico2',
            name='Ambito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico2',
            name='Articulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico2',
            name='FundamentoPlazoMaximo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fundamento del plazo máximo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico2',
            name='Nombre',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico2',
            name='Tipo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico3',
            name='Ambito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico3',
            name='Articulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico3',
            name='FundamentoInformacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fundamento del requerimiento de conservar información'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico3',
            name='Nombre',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico3',
            name='Tipo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico4',
            name='Ambito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico4',
            name='Articulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico4',
            name='FundamentoInspeccion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fundamento de la inspección, verificación o visita domiciliaria'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico4',
            name='Nombre',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico4',
            name='Tipo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico5',
            name='Ambito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico5',
            name='Articulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico5',
            name='FundamentoTramiteOServicio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fundamento que da origen al trámite o servicio'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico5',
            name='Nombre',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico5',
            name='Tipo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico6',
            name='Ambito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico6',
            name='Articulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico6',
            name='FundamentoCriterio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fundamento del criterio de resolución'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico6',
            name='Nombre',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico6',
            name='Tipo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico7',
            name='Ambito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico7',
            name='Articulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico7',
            name='FundamentoDerechos',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fundamento del monto de los derechos'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico7',
            name='Nombre',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico7',
            name='Tipo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico8',
            name='Ambito',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ámbito'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico8',
            name='Articulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico8',
            name='FundamentoCanal',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fundamento del canal de atención'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico8',
            name='Nombre',
            field=models.TextField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fundamentojuridico8',
            name='Tipo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='Informacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Información adicional'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='InformacionInteresado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Información que sea útil para que el interesado realice el trámite'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='ProtestaCiudadana',
            field=models.CharField(blank=True, max_length=100, verbose_name='Protesta Ciudadana'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='ProtestasAnual',
            field=models.IntegerField(blank=True, verbose_name='Cantidad de protestas recibidas al año'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='ConservarInformacion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='TramiteInformacion',
            field=models.TextField(blank=True, max_length=300, verbose_name='¿Este trámite o servicio requiere conservar información para fines de acreditación, inspección y verificación con motivo del trámite o servicio?'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Cargo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='CorreoElectronico',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='DatosResponsable',
            field=models.CharField(blank=True, max_length=200, verbose_name='Datos de la oficina del responsable del trámite'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Extension',
            field=models.IntegerField(blank=True, verbose_name='Extensión'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Otro',
            field=models.CharField(blank=True, max_length=30, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='QuejasDenuncias',
            field=models.TextField(blank=True, max_length=400, verbose_name='Datos de contacto para quejas y denuncias'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='ResponsableTramite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable del trámite o servicio'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='RolFuncionario',
            field=models.CharField(blank=True, max_length=30, verbose_name='Rol del funcionario'),
        ),
        migrations.AlterField(
            model_name='responsableresolucion',
            name='Telefono',
            field=models.IntegerField(blank=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='ActividadEconomica',
            field=models.TextField(blank=True, max_length=300, verbose_name='Actividad económica que está vinculada al trámite o servicio'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='CasoSolicitud',
            field=models.CharField(blank=True, max_length=150, verbose_name='¿En qué caso se debe solicitar el trámite o servicio?'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Clase',
            field=models.CharField(blank=True, max_length=200, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Detalle',
            field=models.TextField(blank=True, max_length=500, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='FuncionalidadTramite',
            field=models.TextField(blank=True, max_length=400, verbose_name='¿Para qué sirve realizar este trámite?'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='LigaResolucion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Liga de la resolución del trámite'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='LigaTramite',
            field=models.CharField(blank=True, max_length=200, verbose_name='Liga del trámite con que está vincualdo'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Rama',
            field=models.TextField(blank=True, max_length=300, verbose_name='Rama'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Resolucion',
            field=models.TextField(blank=True, max_length=300, verbose_name='La resolución de este trámite está vinculada con la presentación de otros trámites'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='ResolucionRequisito',
            field=models.CharField(blank=True, max_length=2, verbose_name='La resolución es requisito de otro trámite'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Subrama',
            field=models.CharField(blank=True, max_length=150, verbose_name='Subrama'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='Subsector',
            field=models.TextField(blank=True, max_length=350, verbose_name='Subsector'),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='DerechoRespuesta',
            field=models.CharField(blank=True, max_length=30, verbose_name='Derecho del usuario ante la falta de respuesta'),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='PlazoPrevenir',
            field=models.CharField(blank=True, max_length=100, verbose_name='Plazo que tiene la dependencia para prevenir'),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='PlazoResponder',
            field=models.IntegerField(blank=True, verbose_name='Plazo que tiene el usuario para responder la prevención'),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='TiempoResolucion',
            field=models.IntegerField(blank=True, verbose_name='Tiempo que tiene la dependencia para resolver'),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='Vigencia',
            field=models.CharField(blank=True, max_length=30, verbose_name='Vigencia'),
        ),
    ]
