# Generated by Django 4.1 on 2022-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_estadistica_totalsolicitudesrecibidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='TiempoPromedio',
            field=models.IntegerField(blank=True, verbose_name='Tiempo promedio en conseguir el requisito para su presentación (días)'),
        ),
    ]
