# Generated by Django 4.1 on 2022-08-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_agendarcita_cita_agendar_cita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundamentojuridico6',
            old_name='Ambito',
            new_name='ambito',
        ),
        migrations.RenameField(
            model_name='fundamentojuridico6',
            old_name='Articulo',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='fundamentojuridico6',
            old_name='FundamentoCriterio',
            new_name='fundamentoCriterio',
        ),
        migrations.RenameField(
            model_name='fundamentojuridico6',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='fundamentojuridico6',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
