# Generated by Django 4.1 on 2022-08-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_ambito_datogeneral_formapago_modalidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_requisito', models.CharField(max_length=160, verbose_name='Nombre del requisito')),
            ],
        ),
        migrations.DeleteModel(
            name='Pasos',
        ),
        migrations.DeleteModel(
            name='SINO',
        ),
        migrations.RenameField(
            model_name='datogeneral',
            old_name='regristro_regulaciones',
            new_name='registro_regulaciones_canal',
        ),
        migrations.RemoveField(
            model_name='datogeneral',
            name='OriginalCopia',
        ),
        migrations.RemoveField(
            model_name='datogeneral',
            name='agendar_cita',
        ),
        migrations.RemoveField(
            model_name='datogeneral',
            name='ambito',
        ),
        migrations.RemoveField(
            model_name='datogeneral',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='datogeneral',
            name='fundamentoCriterio',
        ),
        migrations.RemoveField(
            model_name='datogeneral',
            name='fundamentoTramiteOServicio',
        ),
        migrations.RemoveField(
            model_name='datogeneral',
            name='fundamento_plazoMaximo',
        ),
        migrations.RemoveField(
            model_name='datogeneral',
            name='realizar_tramite',
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='ambito_canal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ámbito'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='ambito_criterio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ámbito'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='ambito_derechos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ámbito'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='ambito_informacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ámbito'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='ambito_inspeccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ámbito'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='ambito_plazo_maximo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ámbito'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='ambito_tramite_servicio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ámbito'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='ambito_vigencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ámbito'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='articulo_canal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='articulo_criterio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='articulo_derechos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='articulo_informacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='articulo_inspeccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='articulo_plazo_maximo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='articulo_tramite_servicio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='articulo_vigencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='descripcion_requisito',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='fundamento_criterio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundamento del criterio de resolución'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='fundamento_plazo_maximo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundamento del plazo máximo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='fundamento_tramite_servicio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundamento que da origen al trámite o servicio'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_canal',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_criterio',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_derechos',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_informacion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_inspeccion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_plazo_maximo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_tramite_servicio',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_vigencia',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='original_copia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.originalcopia', verbose_name='Original o copia'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='puede_agendar_cita',
            field=models.BooleanField(default=False, verbose_name='¿Es obligatorio agendar una cita?'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='puede_realizar_tramite',
            field=models.BooleanField(default=False, verbose_name='¿Se puede agendar una cita para realizar un trámite?'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='tipo_canal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='tipo_criterio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='tipo_derechos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='tipo_informacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='tipo_inspeccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='tipo_plazo_maximo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='tipo_tramite_servicio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='datogeneral',
            name='tipo_vigencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ambito',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='actividad_economica',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Actividad económica que está vinculada al trámite o servicio'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='caso_solicitud',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='¿En qué caso se debe solicitar el trámite o servicio?'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='clase',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='conservar_informacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='datos_responsable',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Datos de la oficina del responsable del trámite'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='derecho_respuesta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Derecho del usuario ante la falta de respuesta'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='detalle',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='etapa_tramite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etapa del trámite o servicio en que se realiza o se puede realizar el trámite'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='extension',
            field=models.IntegerField(blank=True, null=True, verbose_name='Extensión'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='firma_validacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='¿Es necesario alguna firma, validación, certificación, autorización o visto bueno de un tercero?'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='formato',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Forma parte del formato'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='funcionalidad_tramite',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='¿Para qué sirve realizar este trámite?'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_canal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundamento del canal de atención'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_derechos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundamento del monto de los derechos'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_informacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundamento del requerimiento de conservar información'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_inspeccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundamento de la inspección, verificación o visita domiciliaria'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_vigencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundamento de la vigencia'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='informacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Información adicional'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='informacion_interesado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Información que sea útil para que el interesado realice el trámite'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='liga_resolucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Liga de la resolución del trámite'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='liga_tramite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Liga del trámite con que está vincualdo'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='medio_cita',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Medio para solicitar la cita'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.ambito', verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='naturaleza',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Naturaleza'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='nivel_gobierno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.niveldegobierno', verbose_name='Nivel de gobierno'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='nombre_dependencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la dependencia, ubicación y medios de contacto'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='nombre_formato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del formato'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='organo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Órgano interno de control'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='otro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='persona_emite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la empresa o persona que lo emite'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='plazo_prevenir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plazo que tiene la dependencia para prevenir'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='plazo_responder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo que tiene el usuario para responder la prevención'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='protesta_anual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de protestas recibidas al año'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='protesta_ciudadana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Protesta Ciudadana'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='quejas_denuncias',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Datos de contacto para quejas y denuncias'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='rama',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Rama'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='realizar_pago',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='¿En dónde puedo realizar el pago?'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='requisito_solicitado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='¿El requisito solicitado es un trámite que se debe realizar con alguna dependencia gubernamental?'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='resolucion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='La resolución de este trámite está vinculada con la presentación de otros trámites'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='resolucion_requisito',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='La resolución es requisito de otro trámite'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='responsable_tramite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable del trámite o servicio'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='rol_funcionario',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Rol del funcionario'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='solicitudes_recibidas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de solicitudes recibidas en el año anterior'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='subrama',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Subrama'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='subsector',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='Subsector'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='tiempo_promedio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo promedio en conseguir el requisito para su presentación (horas)'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='tiempo_resolucion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo que tiene la dependencia para resolver'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.tipo'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='tipo_tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.tipotramite', verbose_name='Tipo de trámite'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='total_solicitudes_recibidas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de solicitudes recibidas'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='tramite_informacion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='¿Este trámite o servicio requiere conservar información para fines de acreditación, inspección y verificación con motivo del trámite o servicio?'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='vigencia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Vigencia'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='vigencia_pago',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Vigencia de la línea de captura para realizar el pago en caso de requerirla'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='niveldegobierno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordenamientojuridico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='originalcopia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tiporesolucion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tiposolicitante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipotramite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ubicacionespago',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='nombre_requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.requisito'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='pasos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.paso', verbose_name='Pasos'),
        ),
    ]
