# Generated by Django 4.1 on 2022-08-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_paso_requisito_delete_pasos_delete_sino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordenamientojuridico',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='originalcopia',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paso',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tiporesolucion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tiposolicitante',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipotramite',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ubicacionespago',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
