# Generated by Django 4.1 on 2022-08-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_formapago_nombre_alter_modalidad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datogeneral',
            name='homoclave_anterior',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Homoclave'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='homoclave',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Homoclave nueva'),
        ),
    ]
