# Generated by Django 4.1 on 2022-08-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_datogeneral_homoclave_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datogeneral',
            name='requisito',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='caso_solicitud',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='¿En qué caso se debe solicitar el trámite o servicio?'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_canal',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Fundamento del canal de atención'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_criterio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Fundamento del criterio de resolución'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_derechos',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Fundamento del monto de los derechos'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_informacion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Fundamento del requerimiento de conservar información'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_inspeccion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Fundamento de la inspección, verificación o visita domiciliaria'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_plazo_maximo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Fundamento del plazo máximo'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_tramite_servicio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Fundamento que da origen al trámite o servicio'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='fundamento_vigencia',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Fundamento de la vigencia'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='homoclave',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Homoclave'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='homoclave_anterior',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Homoclave anterior'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='modalidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='monto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='nombre_requisito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.requisito'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='numero_identificador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de identificador del formato'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='registro_regulaciones_canal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro de regulaciones'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='rol_funcionario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol del funcionario'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='tipo_resolucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de resolución'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='vigencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vigencia'),
        ),
        migrations.AlterField(
            model_name='datogeneral',
            name='vigencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vigencia de la línea de captura para realizar el pago en caso de requerirla'),
        ),
    ]
